apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
  - image: nginx
    env:
    - name: APP_COLOR
      value: blue
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_ENV
    envFrom:
      configMapRef:
        name: app-config
